services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'cultureamp/docker-manifest']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
